In [1]:
import numpy as np
import torch
import torch.nn
import torch.optim as optim
import os
import pandas as pd
import math
print(torch.__version__)
print(torch.device("cpu"))

:

:

In [2]:
import os
import pandas as pd 
DATA_PATH = os.path.join(os.environ['DATA_ROOT'], "lichess-01-23", "samples")
DATA_FILE = os.path.join(
    DATA_PATH,
    "small_sample.parquet"
)
data_df = pd.read_parquet(DATA_FILE)
display(data_df.head(2))

data_df = data_df[["Result", "BlackElo", "WhiteElo", "Termination", "TimeControl", "moves"]]
display(data_df.head(2))

,Event,Site,Date,Round,White,Black,Result,BlackElo,BlackRatingDiff,ECO,Opening,Termination,TimeControl,UTCDate,UTCTime,WhiteElo,WhiteRatingDiff,moves,WhiteTitle,BlackTitle
0,Rated Blitz game,https://lichess.org/7BVUSJXz,2023.01.01,-,Si6gma,Materiagris,0-1,1470,+5,B08,Pirc Defense: Classical Variation,Normal,300+3,2023.01.01,11:08:50,1443,-5,1. e4 { [%clk 0:05:00] } 1... g6 { [%clk 0:05:...,None,None
1,Rated Bullet game,https://lichess.org/ON36RPCG,2023.01.01,-,SuiRenji_Salem,EagleFarouk,0-1,2103,+5,A06,Zukertort Opening: Tennison Gambit,Time forfeit,60+0,2023.01.01,02:38:01,2086,-5,1. e4 { [%clk 0:01:00] } 1... d5 { [%clk 0:01:...,None,None

,Result,BlackElo,WhiteElo,Termination,TimeControl,moves
0,0-1,1470,1443,Normal,300+3,1. e4 { [%clk 0:05:00] } 1... g6 { [%clk 0:05:...
1,0-1,2103,2086,Time forfeit,60+0,1. e4 { [%clk 0:01:00] } 1... d5 { [%clk 0:01:...

In [3]:
def softmax(Z):
    """
    Z: (batch_size, seq_len, seq_len)
    """
    Z = Z - Z.max(axis=-1, keepdims=True)
    return np.exp(Z) / Z.sum(axis=-1, keepdims=True)

def self_attention(X, mask, W_KQV, Wout):
    """ 
    X: (batch_size, seq_len, d_model)
    mask: (batch_size, seq_len)
    W_KQV: (d_model, 3*d_model)
    Wout: (d_model, d_model)
    """
    K, Q, V = np.split(X @ W_KQV, 3, axis=1)
    attn = softmax(K @ Q.T / np.sqrt(X.shape[1]) + mask)
    return attn @ V @ Wout, attn

In [5]:
T, d = 100, 64
attn = torch.nn.MultiheadAttention(d, 1, bias=False, batch_first=True)
M = torch.triu(-float("inf")*torch.ones(T, T), 1)
X = torch.randn(1, T, d)
Y_, A_ = attn(X, X, X, attn_mask=M)

:

:

In [6]:
attn.in_proj_weight.shape

torch.Size([192, 64])

In [4]:
Y, A = self_attention(X[0].numpy(), M.numpy())

NameError: name 'X' is not defined

In [1]:
import os
print(os.environ['PYTORCH_METAL'])

1